### ISSUE TITLE
Review + publish alpha data (email alpha testers)

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/connect#32]
I have some bandwidth this sprint and it seems like the right time to evaluate.

**Comment by daguar** [comment]
- Added "email alpha testers" to this issue (tell them what we learned)
- Reassigned this issue to myself

**Comment by daguar** [comment]
New calculations made and email sent to the SF Food Bank testers (with corgi pup). Only lingering thing here might be to email the non-Food Bank folks that Liliana solicited (I noted this and asked Liliana if I could email them the results too).
