### ISSUE TITLE
Ruby 2.1.1 should now be 2.1.6 to work properly in Heroku

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/connect#40]
```
 !     An error occurred while installing Ruby ruby-2.1.1
 !     For supported Ruby versions see https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
 !     Note: Only the most recent version of Ruby 2.1 is supported on Cedar-14
 !     Command: 'set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.1.1.tgz -s -o - | tar zxf - ' failed unexpectedly:
```

Can send a pull request on the gemfile and docs if that'll help.

**Comment by alanjosephwilliams** [comment]
Classic Cedar 14

**Comment by daguar** [comment]
Thanks @ErnieAtLYD! I've encountered this before with other apps, and yeah we should bump versions.

For now, I recommend you just change the Gemfile, run `bundle install`, commit the change and push. Also, awesome that y'all are trying it out!

**Comment by ErnieAtLYD** [comment]
We are! We're trying to do a spin-off to see if this can be re-purposed to do callbacks from San Francisco's 311 systems. @mathias-gibson has the full details; we may be pinging you guys often. :)

**Comment by pearlymaccha** [comment]
I got the same problem, how to fix this? Thank you

**Comment by daguar** [comment]
Hey @pearlymaccha — the way to fix this is to change the line in the Gemfile to `ruby '2.1.6`. A pull request would also be welcome ( @ErnieAtLYD if you did this, I'd be happy to merge.)

**Comment by pearlymaccha** [comment]
Ok I got it, thanks @daguar
